### ISSUE TITLE
Trendie

### ISSUE THREAD

**Issue by Lorraine1511** [EOSIO/EEPs#8]
EEP-1 Proposal

Cyber Pollution we need to create a team not just for Abuse of Cyber Space but filter all spam and unnecessary forks in coding simplify measures by creating one rythem in the fork and duplicate the response in each block.

Lorraine151

**Comment by sanaraufx** [comment]
Thanks for this suggestion. If you'd like to submit this as an EEP, please check out our EEP-1 Purpose and Guidelines and submit your proposal?
